2_1_simplemodels
thinknetica-django-lab-02/jenbonik pull request #13
Opened 2021-03-25 17:29 UTC by jenbonik

Close #4

2021-03-26 07:51 UTC, morgangt requested changes

2021-03-26 07:51 UTC, morgangt commented on luckydeal/main/models.py
> +class Good(BaseIdentificatedObject):
давайте описывать docstring  к классам модели, так сможем лучше документировать код
https://www.python.org/dev/peps/pep-0257/

2021-03-26 07:51 UTC, morgangt commented on luckydeal/main/models.py
> +class BaseIdentificatedObject(models.Model):
лучше подойдет название для модели Identificated потому что речь идет об одном Идентификаторе

2021-03-26 13:59 UTC, jenbonik commented on luckydeal/main/models.py
> +class Good(BaseIdentificatedObject):
Сделал.

2021-03-26 14:00 UTC, jenbonik commented on luckydeal/main/models.py
> +class BaseIdentificatedObject(models.Model):
Да, с наванием были сложности. Хотелось обеспечить первичные ключи и не писать одинаковые поля в каждой модели

2021-03-30 15:58 UTC, morgangt approved these changes

2021-03-30 17:50 UTC, merged